Numpy is suitable for dealing with homogeneously typed numerical array data, Pandas for tabular or heterogeneous data.

In [1]:
import numpy as np
import pandas as pd

# Series (values + index)

In [2]:
obj = pd.Series([4, 7, -5, 3])
obj

0    4
1    7
2   -5
3    3
dtype: int64

In [3]:
obj.array  # Get data

<NumpyExtensionArray>
[np.int64(4), np.int64(7), np.int64(-5), np.int64(3)]
Length: 4, dtype: int64

In [4]:
obj.index  # Get index

RangeIndex(start=0, stop=4, step=1)

Usually, index consists of the integers from 0 through N-1 by default

In [5]:
obj2 = pd.Series([4, 7, -5, 3], index=['d', 'b', 'a', 'c'])  # Change index 
obj2

d    4
b    7
a   -5
c    3
dtype: int64

In [6]:
obj2.index

Index(['d', 'b', 'a', 'c'], dtype='object')

You can use labels in the index when selecting **single values** or **a set of values**

In [7]:
obj2["a"]

np.int64(-5)

In [8]:
obj2["d"] = 6
obj2[["c", "a", "d"]]

c    3
a   -5
d    6
dtype: int64

In [9]:
obj2[obj2 > 0]  # Boolean array

d    6
b    7
c    3
dtype: int64

In [10]:
obj2 * 2  # scalar function 

d    12
b    14
a   -10
c     6
dtype: int64

In [11]:
np.exp(obj2)

d     403.428793
b    1096.633158
a       0.006738
c      20.085537
dtype: float64

In [12]:
"b" in obj2  # As dictionary "mapping"

True

In [13]:
"e" in obj2

False

In [14]:
sdata = {"Ohio": 35000, "Texas": 71000, "Oregon": 16000, "Utab": 5000}
obj3 = pd.Series(sdata)  # dictionary to Series
obj3

Ohio      35000
Texas     71000
Oregon    16000
Utab       5000
dtype: int64

In [15]:
obj3.to_dict()  # Series to dictionary 

{'Ohio': 35000, 'Texas': 71000, 'Oregon': 16000, 'Utab': 5000}

In [16]:
states = ("California", "Ohio", "Oregon", "Texas")
obj4 = pd.Series(sdata, index=states)
obj4

California        NaN
Ohio          35000.0
Oregon        16000.0
Texas         71000.0
dtype: float64

In [17]:
pd.isna(obj4)  # Detect missing data

California     True
Ohio          False
Oregon        False
Texas         False
dtype: bool

In [18]:
pd.notna(obj4)

California    False
Ohio           True
Oregon         True
Texas          True
dtype: bool

In [19]:
obj4.isna()

California     True
Ohio          False
Oregon        False
Texas         False
dtype: bool

Series automatically **aligns by index**
Key: 'obj3+obj4' gives NaN for Utah
Reason: Utah is only in obj3, obj4 has no value(NaN)

In [20]:
obj3

Ohio      35000
Texas     71000
Oregon    16000
Utab       5000
dtype: int64

In [21]:
obj4

California        NaN
Ohio          35000.0
Oregon        16000.0
Texas         71000.0
dtype: float64

In [22]:
obj3 + obj4

California         NaN
Ohio           70000.0
Oregon         32000.0
Texas         142000.0
Utab               NaN
dtype: float64

In [23]:
obj4.name = "population"
obj4.index.name = "state"
obj4

state
California        NaN
Ohio          35000.0
Oregon        16000.0
Texas         71000.0
Name: population, dtype: float64

Series's index can be altered in place by assignment

In [24]:
obj

0    4
1    7
2   -5
3    3
dtype: int64

In [25]:
obj.index = ["Bob", "Steven", "Jeff", "Ryan"]

In [26]:
obj

Bob       4
Steven    7
Jeff     -5
Ryan      3
dtype: int64

# DataFrame

In [27]:
data = {"state": ["Ohio", "Ohio", "Ohio", "Nevada", "Nevada", "Nevada"],
        "year": [2000, 2001, 2002, 2001, 2002, 2003],
        "pop": [1.5, 1.7, 3.6, 2.4, 2.9, 3.2]}
frame = pd.DataFrame(data)

In [28]:
frame

state  year  pop
0    Ohio  2000  1.5
1    Ohio  2001  1.7
2    Ohio  2002  3.6
3  Nevada  2001  2.4
4  Nevada  2002  2.9
5  Nevada  2003  3.2

In [29]:
frame.head()  # The first five rows

state  year  pop
0    Ohio  2000  1.5
1    Ohio  2001  1.7
2    Ohio  2002  3.6
3  Nevada  2001  2.4
4  Nevada  2002  2.9

In [30]:
frame.tail()  # The last five rows

state  year  pop
1    Ohio  2001  1.7
2    Ohio  2002  3.6
3  Nevada  2001  2.4
4  Nevada  2002  2.9
5  Nevada  2003  3.2

In [31]:
pd.DataFrame(data, columns=["year", "state", "pop"])

year   state  pop
0  2000    Ohio  1.5
1  2001    Ohio  1.7
2  2002    Ohio  3.6
3  2001  Nevada  2.4
4  2002  Nevada  2.9
5  2003  Nevada  3.2

In [32]:
frame2 = pd.DataFrame(data, columns=["year", "state", "pop", "debt"])  # If column is not in frame,then it will be NaN
frame2

year   state  pop debt
0  2000    Ohio  1.5  NaN
1  2001    Ohio  1.7  NaN
2  2002    Ohio  3.6  NaN
3  2001  Nevada  2.4  NaN
4  2002  Nevada  2.9  NaN
5  2003  Nevada  3.2  NaN

In [33]:
frame2.columns

Index(['year', 'state', 'pop', 'debt'], dtype='object')

In [34]:
frame2["state"]

0      Ohio
1      Ohio
2      Ohio
3    Nevada
4    Nevada
5    Nevada
Name: state, dtype: object

In [35]:
frame2.year

0    2000
1    2001
2    2002
3    2001
4    2002
5    2003
Name: year, dtype: int64

Note:`frame2[column]`works for any column name,but `frame2.column`works only when the column name is valid variable name (default fetch column)

In [36]:
frame2.loc[2]

year     2002
state    Ohio
pop       3.6
debt      NaN
Name: 2, dtype: object

In [37]:
frame2.iloc[1]

year     2001
state    Ohio
pop       1.7
debt      NaN
Name: 1, dtype: object

In [38]:
frame2["debt"] = 16.5
frame2

year   state  pop  debt
0  2000    Ohio  1.5  16.5
1  2001    Ohio  1.7  16.5
2  2002    Ohio  3.6  16.5
3  2001  Nevada  2.4  16.5
4  2002  Nevada  2.9  16.5
5  2003  Nevada  3.2  16.5

In [39]:
frame2["debt"] = np.arange(6.)
frame2

year   state  pop  debt
0  2000    Ohio  1.5   0.0
1  2001    Ohio  1.7   1.0
2  2002    Ohio  3.6   2.0
3  2001  Nevada  2.4   3.0
4  2002  Nevada  2.9   4.0
5  2003  Nevada  3.2   5.0

In [40]:
val = pd.Series([-1.2, -1.5, -1.7], index=[2, 4, 5])
frame2["debt"] = val
frame2

year   state  pop  debt
0  2000    Ohio  1.5   NaN
1  2001    Ohio  1.7   NaN
2  2002    Ohio  3.6  -1.2
3  2001  Nevada  2.4   NaN
4  2002  Nevada  2.9  -1.5
5  2003  Nevada  3.2  -1.7

In [41]:
frame2["eastern"] = frame2["state"] == "Ohio"
frame2

year   state  pop  debt  eastern
0  2000    Ohio  1.5   NaN     True
1  2001    Ohio  1.7   NaN     True
2  2002    Ohio  3.6  -1.2     True
3  2001  Nevada  2.4   NaN    False
4  2002  Nevada  2.9  -1.5    False
5  2003  Nevada  3.2  -1.7    False

In [42]:
del frame2["eastern"]
frame2.columns

Index(['year', 'state', 'pop', 'debt'], dtype='object')

Nested dictionary

In [43]:
populations = {"Ohio": {2000: 1.5, 2001: 1.7, 2002: 3.6},
               "Nevada": {2001: 2.4, 2002: 2.9}}
frame3 = pd.DataFrame(populations)
frame3

Ohio  Nevada
2000   1.5     NaN
2001   1.7     2.4
2002   3.6     2.9

In [44]:
frame3.T

2000  2001  2002
Ohio     1.5   1.7   3.6
Nevada   NaN   2.4   2.9

If you transpose twice, it changes the data type

In [45]:
populations

{'Ohio': {2000: 1.5, 2001: 1.7, 2002: 3.6}, 'Nevada': {2001: 2.4, 2002: 2.9}}

In [46]:
pd.DataFrame(populations, index=[2001, 2002, 2003])  # Use index in the inner dictionary

Ohio  Nevada
2001   1.7     2.4
2002   3.6     2.9
2003   NaN     NaN

In [47]:
frame3

Ohio  Nevada
2000   1.5     NaN
2001   1.7     2.4
2002   3.6     2.9

Slicing: [start:stop:step]

In [48]:
pdata = {"Ohio": frame3["Ohio"][:-1], "Nevada": frame3["Nevada"][:2]}
pd.DataFrame(pdata)

Ohio  Nevada
2000   1.5     NaN
2001   1.7     2.4

**DataFrame input**

In [49]:
# 1.2D ndarray
data = np.array([[1, 2], [3, 4]])
df1 = pd.DataFrame(data, index=["X", "Y"], columns=["A", "B"])
df1

A  B
X  1  2
Y  3  4

In [50]:
# 2.Dictionary of arrays,lists or tuples
data = {"A": [1, 2, 3], "B": [4, 5, 6]}
df3 = pd.DataFrame(data)
df3

A  B
0  1  4
1  2  5
2  3  6

In [51]:
# 3. NumPy structured/record array
data = np.array([(1, 'a'), (2, 'b')], dtype=[('num', 'i4'), ('letter', 'U1')])
df4 = pd.DataFrame(data)
df4

num letter
0    1      a
1    2      b

In [52]:
# 4.Dictionary of Series
s1 = pd.Series([1, 2], index=['a', 'b'])
s2 = pd.Series([3, 4], index=['b', 'c'])
df5 = pd.DataFrame({'A': s1, 'B': s2})
df5

A    B
a  1.0  NaN
b  2.0  3.0
c  NaN  4.0

In [53]:
# 5.Dictionary of dictionaries
data = {'Ohio': {2001: 1.7, 2002: 3.6}, 'Nevada': {2001: 2.4}}
pd6 = pd.DataFrame(data)
pd6

Ohio  Nevada
2001   1.7     2.4
2002   3.6     NaN

In [54]:
# 6.List of dictionaries or Series
data = [{'A': 1, 'B': 2}, {'A': 3, 'B': 4}]
df7 = pd.DataFrame(data)
df7

A  B
0  1  2
1  3  4

In [55]:
# 7.List of  lists or tuples
data = [[1, 2], [3, 4]]
df8 = pd.DataFrame(data, columns=['A', 'B'])
df8

A  B
0  1  2
1  3  4

In [56]:
# 8.Another DataFrame
df9_1 = pd.DataFrame({'A': [1, 2]})
df9_2 = pd.DataFrame(df9_1)
df9_2

A
0  1
1  2

In [57]:
# 9.NumPy MaskedArray  
# Mask part into NaN
import numpy.ma as ma

data = ma.array([[1, 2], [3, 4]], mask=[[0, 1], [0, 0]])
df10 = pd.DataFrame(data)
df10

0    1
0  1.0  NaN
1  3.0  4.0

DataFrame's index and columns

In [58]:
frame3

Ohio  Nevada
2000   1.5     NaN
2001   1.7     2.4
2002   3.6     2.9

In [59]:
frame3.index.name = "year"
frame3.columns.name = "state"
frame3

state  Ohio  Nevada
year               
2000    1.5     NaN
2001    1.7     2.4
2002    3.6     2.9

In [60]:
frame3.to_numpy()

array([[1.5, nan],
       [1.7, 2.4],
       [3.6, 2.9]])

In [61]:
frame2

year   state  pop  debt
0  2000    Ohio  1.5   NaN
1  2001    Ohio  1.7   NaN
2  2002    Ohio  3.6  -1.2
3  2001  Nevada  2.4   NaN
4  2002  Nevada  2.9  -1.5
5  2003  Nevada  3.2  -1.7

In [62]:
frame2.to_numpy()  # Returns a data type compatible with all columns

array([[2000, 'Ohio', 1.5, nan],
       [2001, 'Ohio', 1.7, nan],
       [2002, 'Ohio', 3.6, -1.2],
       [2001, 'Nevada', 2.4, nan],
       [2002, 'Nevada', 2.9, -1.5],
       [2003, 'Nevada', 3.2, -1.7]], dtype=object)

# Index Objects

In [63]:
obj = pd.Series(np.arange(3), index=["a", "b", "c"])
index = obj.index
index

Index(['a', 'b', 'c'], dtype='object')

In [64]:
index[1:]

Index(['b', 'c'], dtype='object')

In [65]:
index[1] = "d"  # Index objects are immutable and thus can't be modified by the user

TypeError: Index does not support mutable operations

In [ ]:
frame3

In [ ]:
frame3.columns

In [ ]:
"Ohio" in frame3.columns

In [ ]:
2003 in frame3.index

A pandas index can contain duplicate labels

In [ ]:
pd.Index(["foo", "foo", "bar", "bar"])

Selections with duplicate labels will select all occurrences of that label

Index Methods and Properties
**append()**: Add another Index (e.g., [1, 2] + [3, 4] = [1, 2, 3, 4]).
**difference()**: What’s in this but not that (e.g., [1, 2] - [2, 3] = [1]).
**intersection()**: Common parts (e.g., [1, 2] & [2, 3] = [2]).
**union()**: Combine all (e.g., [1, 2] | [2, 3] = [1, 2, 3]).
**isin()**: Check if in list (e.g., [1, 2].isin([2]) = [False, True]).
**drop()**: Remove value (e.g., drop 2 from [1, 2, 3] = [1, 3]).

# Essential functionality

In [66]:
obj = pd.Series([4.5, 7.2, -5.3, 3.6], index=["d", "b", "a", "c"])
obj

d    4.5
b    7.2
a   -5.3
c    3.6
dtype: float64

In [67]:
obj2 = obj.reindex(["a", "b", "c", "d", "e"])
obj2

a   -5.3
b    7.2
c    3.6
d    4.5
e    NaN
dtype: float64

In [68]:
obj3 = pd.Series(["blue", "purple", "yellow"], index=[0, 2, 4])
obj3

0      blue
2    purple
4    yellow
dtype: object

In [69]:
obj3.reindex(np.arange(6), method='ffill')  # ffill:forward-fills the value

0      blue
1      blue
2    purple
3    purple
4    yellow
5    yellow
dtype: object

In [70]:
frame = pd.DataFrame(np.arange(9).reshape((3, 3)), index=["a", "c", "d"], columns=["Ohio", "Texas", "California"])
frame

Ohio  Texas  California
a     0      1           2
c     3      4           5
d     6      7           8

In [71]:
frame2 = frame.reindex(index=["a", "b", "c", "d"])
frame2

Ohio  Texas  California
a   0.0    1.0         2.0
b   NaN    NaN         NaN
c   3.0    4.0         5.0
d   6.0    7.0         8.0

In [72]:
states = ["Texas", "Utah", "California"]
frame.reindex(columns=states)

Texas  Utah  California
a      1   NaN           2
c      4   NaN           5
d      7   NaN           8

In [73]:
frame.reindex(states, axis="columns")

Texas  Utah  California
a      1   NaN           2
c      4   NaN           5
d      7   NaN           8

**labels/index**: New row labels (e.g., ['a', 'c']).
**columns**: New column labels (e.g., ['A', 'B']).
**method**: Fill missing (ffill=forward, bfill=backward).
**fill_value**: What to fill (e.g., 0 instead of NaN).

In [74]:
frame

Ohio  Texas  California
a     0      1           2
c     3      4           5
d     6      7           8

In [75]:
frame.loc[["a", "d", "c"], ["California", "Texas"]]

California  Texas
a           2      1
d           8      7
c           5      4

# Dropping Entries from an Axis

In [76]:
obj = pd.Series(np.arange(5.), index=["a", "b", "c", "d", "e"])
obj

a    0.0
b    1.0
c    2.0
d    3.0
e    4.0
dtype: float64

In [77]:
new_obj = obj.drop("c")
new_obj

a    0.0
b    1.0
d    3.0
e    4.0
dtype: float64

In [78]:
data = pd.DataFrame(np.arange(16).reshape((4, 4)),
                    index=["Ohio", "Colorado", "Utah", "New York"],
                    columns=["one", "two", "three", "four"])

In [79]:
data.drop(index=["Colorado", "Ohio"])

one  two  three  four
Utah        8    9     10    11
New York   12   13     14    15

In [80]:
data.drop(columns=["two"])

one  three  four
Ohio        0      2     3
Colorado    4      6     7
Utah        8     10    11
New York   12     14    15

axis=1 equal axis="columns"

In [81]:
data.drop("two", axis=1)

one  three  four
Ohio        0      2     3
Colorado    4      6     7
Utah        8     10    11
New York   12     14    15

In [82]:
data.drop(["two", "four"], axis="columns")

one  three
Ohio        0      2
Colorado    4      6
Utah        8     10
New York   12     14

# Indexing,Selection,and Filtering

In [83]:
obj.loc[["b", "a", "d"]]

b    1.0
a    0.0
d    3.0
dtype: float64

[]（方括号索引）
行为：如果索引是整数，优先按标签取；如果索引是默认整数，则按位置取。

.loc
行为：永远按标签取，跟位置无关。

.iloc
行为：永远按位置取，跟标签无关。

In [84]:
obj1 = pd.Series([1, 2, 3], index=[2, 0, 1])
obj2 = pd.Series([1, 2, 3], index=["a", "b", "c"])

In [85]:
obj1

2    1
0    2
1    3
dtype: int64

In [86]:
obj2

a    1
b    2
c    3
dtype: int64

In [87]:
obj1[[0, 1, 2]]

0    2
1    3
2    1
dtype: int64

In [88]:
obj2[[0, 1, 2]]

C:\Users\Irevin\AppData\Local\Temp\ipykernel_21908\4078289495.py:1: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  obj2[[0, 1, 2]]


a    1
b    2
c    3
dtype: int64

In [89]:
obj2.loc[[0, 1]]

KeyError: "None of [Index([0, 1], dtype='int64')] are in the [index]"

In [90]:
obj1.iloc[[0, 1, 2]]

2    1
0    2
1    3
dtype: int64

In [91]:
obj2.iloc[[0, 1, 2]]

a    1
b    2
c    3
dtype: int64

**Note**:You can also slice with labels, but it works differently from normal Python slicing in that the endpoint is **inclusive**

In [92]:
obj2.loc["b":"c"]

b    2
c    3
dtype: int64

In [93]:
obj2.loc["b":"c"] = 5
obj2

a    1
b    5
c    5
dtype: int64

用data[column_name]（传入列名）时，Pandas会返回对应的列。
用data[start:stop]（切片语法）时，Pandas会按行（row）切片，返回指定范围的行。

In [141]:
data = pd.DataFrame(np.arange(16).reshape((4, 4)),
                    index=["Ohio", "Colorado", "Utah", "New York"],
                    columns=["one", "two", "three", "four"])
data

one  two  three  four
Ohio        0    1      2     3
Colorado    4    5      6     7
Utah        8    9     10    11
New York   12   13     14    15

In [95]:
data["two"]

Ohio         1
Colorado     5
Utah         9
New York    13
Name: two, dtype: int64

In [96]:
data[["three", "one"]]

three  one
Ohio          2    0
Colorado      6    4
Utah         10    8
New York     14   12

In [97]:
data[:2]

one  two  three  four
Ohio        0    1      2     3
Colorado    4    5      6     7

In [98]:
data[data["three"] > 5]

one  two  three  four
Colorado    4    5      6     7
Utah        8    9     10    11
New York   12   13     14    15

In [99]:
data < 5

one    two  three   four
Ohio       True   True   True   True
Colorado   True  False  False  False
Utah      False  False  False  False
New York  False  False  False  False

In [100]:
data[data < 5] = 0
data

one  two  three  four
Ohio        0    0      0     0
Colorado    0    5      6     7
Utah        8    9     10    11
New York   12   13     14    15

In [101]:
data

one  two  three  four
Ohio        0    0      0     0
Colorado    0    5      6     7
Utah        8    9     10    11
New York   12   13     14    15

In [102]:
data.loc["Colorado"]

one      0
two      5
three    6
four     7
Name: Colorado, dtype: int64

In [103]:
data.loc[["Colorado", "New York"]]

one  two  three  four
Colorado    0    5      6     7
New York   12   13     14    15

In [104]:
data.loc["Colorado", ["two", "three"]]

two      5
three    6
Name: Colorado, dtype: int64

In [105]:
data

one  two  three  four
Ohio        0    0      0     0
Colorado    0    5      6     7
Utah        8    9     10    11
New York   12   13     14    15

In [106]:
data.iloc[2]

one       8
two       9
three    10
four     11
Name: Utah, dtype: int64

In [107]:
data.iloc[[2, 1]]

one  two  three  four
Utah        8    9     10    11
Colorado    0    5      6     7

In [108]:
data.iloc[2, [3, 0, 1]]

four    11
one      8
two      9
Name: Utah, dtype: int64

In [109]:
data.iloc[[1, 2], [3, 0, 1]]

four  one  two
Colorado     7    0    5
Utah        11    8    9

In [110]:
data.loc[:"Utah", "two"]

Ohio        0
Colorado    5
Utah        9
Name: two, dtype: int64

In [111]:
data.iloc[:, :3][data.three > 5]

one  two  three
Colorado    0    5      6
Utah        8    9     10
New York   12   13     14

In [112]:
data.loc[data.three >= 2]

one  two  three  four
Colorado    0    5      6     7
Utah        8    9     10    11
New York   12   13     14    15

In [132]:
data

one  two  three  four
Ohio        0    1      2     3
Colorado    4    5      6     7
Utah        8    9     10    11
New York   12   13     14    15

In [142]:
data.loc["one", :] = 1

In [143]:
data

one   two  three  four
Ohio       0.0   1.0    2.0   3.0
Colorado   4.0   5.0    6.0   7.0
Utah       8.0   9.0   10.0  11.0
New York  12.0  13.0   14.0  15.0
one        1.0   1.0    1.0   1.0

In [144]:
data = data.iloc[:-1]

In [145]:
data

one   two  three  four
Ohio       0.0   1.0    2.0   3.0
Colorado   4.0   5.0    6.0   7.0
Utah       8.0   9.0   10.0  11.0
New York  12.0  13.0   14.0  15.0

**Note**: data.loc[data.three == 5]["three"]=6 get the copy of data.loc[data.three == 5] first, so it is not data.loc[data.three == 5, "three"]=6

# Arithmetic and Data Alignment

In [146]:
s1 = pd.Series([7.3, -2.5, 3.4, 1.5], index=["a", "c", "d", "e"])
s2 = pd.Series([-2.1, 3.6, -1.5, 4, 3.1], index=["a", "c", "e", "f", "g"])

In [147]:
s1

a    7.3
c   -2.5
d    3.4
e    1.5
dtype: float64

In [148]:
s2

a   -2.1
c    3.6
e   -1.5
f    4.0
g    3.1
dtype: float64

In [149]:
s1 + s2

a    5.2
c    1.1
d    NaN
e    0.0
f    NaN
g    NaN
dtype: float64

In [150]:
df1 = pd.DataFrame(np.arange(9.).reshape((3, 3)), columns=list("bcd"), index=["Ohio", "Texas", "Colorado"])
df2 = pd.DataFrame(np.arange(12.).reshape((4, 3)), columns=list("bde"), index=["Utah", "Ohio", "Texas", "Oregon"])

In [151]:
df1

b    c    d
Ohio      0.0  1.0  2.0
Texas     3.0  4.0  5.0
Colorado  6.0  7.0  8.0

In [152]:
df2

b     d     e
Utah    0.0   1.0   2.0
Ohio    3.0   4.0   5.0
Texas   6.0   7.0   8.0
Oregon  9.0  10.0  11.0

In [153]:
df1 + df2

b   c     d   e
Colorado  NaN NaN   NaN NaN
Ohio      3.0 NaN   6.0 NaN
Oregon    NaN NaN   NaN NaN
Texas     9.0 NaN  12.0 NaN
Utah      NaN NaN   NaN NaN

# Arithmetic methods with fill values

In [154]:
df1 = pd.DataFrame(np.arange(12.).reshape((3, 4)), columns=list("abcd"))
df2 = pd.DataFrame(np.arange(20.).reshape((4, 5)), columns=list("abcde"))
df2.loc[1, "b"] = np.nan

In [155]:
df1

a    b     c     d
0  0.0  1.0   2.0   3.0
1  4.0  5.0   6.0   7.0
2  8.0  9.0  10.0  11.0

In [156]:
df2

a     b     c     d     e
0   0.0   1.0   2.0   3.0   4.0
1   5.0   NaN   7.0   8.0   9.0
2  10.0  11.0  12.0  13.0  14.0
3  15.0  16.0  17.0  18.0  19.0

In [157]:
df1 + df2

a     b     c     d   e
0   0.0   2.0   4.0   6.0 NaN
1   9.0   NaN  13.0  15.0 NaN
2  18.0  20.0  22.0  24.0 NaN
3   NaN   NaN   NaN   NaN NaN

In [158]:
df1.add(df2, fill_value=0)

a     b     c     d     e
0   0.0   2.0   4.0   6.0   4.0
1   9.0   5.0  13.0  15.0   9.0
2  18.0  20.0  22.0  24.0  14.0
3  15.0  16.0  17.0  18.0  19.0

In [159]:
1 / df1

a         b         c         d
0    inf  1.000000  0.500000  0.333333
1  0.250  0.200000  0.166667  0.142857
2  0.125  0.111111  0.100000  0.090909

In [160]:
df1.rdiv(1)

a         b         c         d
0    inf  1.000000  0.500000  0.333333
1  0.250  0.200000  0.166667  0.142857
2  0.125  0.111111  0.100000  0.090909

In [161]:
df1.reindex(columns=df2.columns, fill_value=0)

a    b     c     d  e
0  0.0  1.0   2.0   3.0  0
1  4.0  5.0   6.0   7.0  0
2  8.0  9.0  10.0  11.0  0

In [162]:
arr = np.arange(12.).reshape((3, 4))
arr

array([[ 0.,  1.,  2.,  3.],
       [ 4.,  5.,  6.,  7.],
       [ 8.,  9., 10., 11.]])

In [163]:
arr[0]

array([0., 1., 2., 3.])

In [164]:
arr - arr[0]

array([[0., 0., 0., 0.],
       [4., 4., 4., 4.],
       [8., 8., 8., 8.]])

In [165]:
frame = pd.DataFrame(np.arange(12.).reshape(4, 3), columns=list("bde"), index=["Utah", "Ohio", "Texas", "Oregon"])
series = frame.iloc[0]

In [166]:
frame

b     d     e
Utah    0.0   1.0   2.0
Ohio    3.0   4.0   5.0
Texas   6.0   7.0   8.0
Oregon  9.0  10.0  11.0

In [167]:
series

b    0.0
d    1.0
e    2.0
Name: Utah, dtype: float64

In [168]:
frame - series

b    d    e
Utah    0.0  0.0  0.0
Ohio    3.0  3.0  3.0
Texas   6.0  6.0  6.0
Oregon  9.0  9.0  9.0

In [169]:
series2 = pd.Series(np.arange(3), index=["b", "e", "f"])
series2

b    0
e    1
f    2
dtype: int64

In [170]:
frame + series2

b   d     e   f
Utah    0.0 NaN   3.0 NaN
Ohio    3.0 NaN   6.0 NaN
Texas   6.0 NaN   9.0 NaN
Oregon  9.0 NaN  12.0 NaN

当DataFrame和Series相加时，Pandas默认将Series的索引与DataFrame的列名（columns）对齐，而不是行索引（index）

In [171]:
series3 = frame["d"]
frame

b     d     e
Utah    0.0   1.0   2.0
Ohio    3.0   4.0   5.0
Texas   6.0   7.0   8.0
Oregon  9.0  10.0  11.0

In [172]:
series3

Utah       1.0
Ohio       4.0
Texas      7.0
Oregon    10.0
Name: d, dtype: float64

In [173]:
frame.sub(series3, axis="index")

b    d    e
Utah   -1.0  0.0  1.0
Ohio   -1.0  0.0  1.0
Texas  -1.0  0.0  1.0
Oregon -1.0  0.0  1.0

# Function Application and Mapping

In [174]:
frame = pd.DataFrame(np.random.standard_normal((4, 3)), columns=list("bde"), index=["Utah", "Ohio", "Texas", "Oregon"])
frame

b         d         e
Utah   -0.702604 -1.398667 -1.209557
Ohio   -0.855926  0.715074 -0.383028
Texas   0.864517 -1.157516  0.651847
Oregon -0.213002  0.753981 -0.640593

In [175]:
np.abs(frame)

b         d         e
Utah    0.702604  1.398667  1.209557
Ohio    0.855926  0.715074  0.383028
Texas   0.864517  1.157516  0.651847
Oregon  0.213002  0.753981  0.640593

In [176]:
def f1(x):
    return x.max() - x.min()

In [177]:
frame.apply(f1)  # apply on every column 

b    1.720443
d    2.152648
e    1.861404
dtype: float64

In [179]:
frame.apply(f1, axis="columns")

Utah      0.696063
Ohio      1.571000
Texas     2.022033
Oregon    1.394574
dtype: float64

In [181]:
def f2(x):
    return pd.Series([x.min(), x.max()], index=["min", "max"])

In [182]:
frame.apply(f2)

b         d         e
min -0.855926 -1.398667 -1.209557
max  0.864517  0.753981  0.651847

In [183]:
def my_format(x):
    return f"{x:.2f}"

In [184]:
frame

b         d         e
Utah   -0.702604 -1.398667 -1.209557
Ohio   -0.855926  0.715074 -0.383028
Texas   0.864517 -1.157516  0.651847
Oregon -0.213002  0.753981 -0.640593

In [185]:
frame.applymap(my_format)

C:\Users\Irevin\AppData\Local\Temp\ipykernel_21908\2069332265.py:1: FutureWarning: DataFrame.applymap has been deprecated. Use DataFrame.map instead.
  frame.applymap(my_format)


b      d      e
Utah    -0.70  -1.40  -1.21
Ohio    -0.86   0.72  -0.38
Texas    0.86  -1.16   0.65
Oregon  -0.21   0.75  -0.64

In [186]:
frame["e"].map(my_format)

Utah      -1.21
Ohio      -0.38
Texas      0.65
Oregon    -0.64
Name: e, dtype: object

# Sortng and Ranking

In [187]:
obj = pd.Series(np.arange(4), index=["d", "a", "b", "c"])
obj

d    0
a    1
b    2
c    3
dtype: int64

In [188]:
obj.sort_index()

a    1
b    2
c    3
d    0
dtype: int64

In [189]:
frame = pd.DataFrame(np.arange(8).reshape((2, 4)),
                     index=["three", "one"],
                     columns=["d", "a", "b", "c"])

In [190]:
frame

d  a  b  c
three  0  1  2  3
one    4  5  6  7

In [191]:
frame.sort_index()

d  a  b  c
one    4  5  6  7
three  0  1  2  3

In [192]:
frame.sort_index(axis="columns")

a  b  c  d
three  1  2  3  0
one    5  6  7  4

In [193]:
frame.sort_index(axis="columns", ascending=False)

d  c  b  a
three  0  3  2  1
one    4  7  6  5

In [194]:
obj = pd.Series([4, 7, -3, 2])
obj.sort_values()

2   -3
3    2
0    4
1    7
dtype: int64

In [195]:
obj = pd.Series([4, np.nan, 7, np.nan, -3, 2])
obj.sort_values()

4   -3.0
5    2.0
0    4.0
2    7.0
1    NaN
3    NaN
dtype: float64

In [196]:
obj.sort_values(na_position="first")

1    NaN
3    NaN
4   -3.0
5    2.0
0    4.0
2    7.0
dtype: float64

In [198]:
frame = pd.DataFrame({"b": [4, 7, -3, 2], "a": [0, 1, 0, 1]})
frame

b  a
0  4  0
1  7  1
2 -3  0
3  2  1

In [199]:
frame.sort_values("b")

b  a
2 -3  0
3  2  1
0  4  0
1  7  1

In [201]:
frame.sort_values(["a", "b"])

b  a
2 -3  0
0  4  0
3  2  1
1  7  1

rank是通过“为各组分配平均排名”的方式破坏平级关系的,
eg:7出现两次，次序分别为6和7，取平均值就是6.5

In [203]:
obj = pd.Series([7, -5, 7, 4, 2, 0, 4])
obj.rank()

0    6.5
1    1.0
2    6.5
3    4.5
4    3.0
5    2.0
6    4.5
dtype: float64

也可以根据值在原数据中出现的顺序给出排名

In [204]:
obj.rank(method="first")

0    6.0
1    1.0
2    7.0
3    4.0
4    3.0
5    2.0
6    5.0
dtype: float64

In [205]:
obj.rank(ascending=False)

0    1.5
1    7.0
2    1.5
3    3.5
4    5.0
5    6.0
6    3.5
dtype: float64

# Axis Indexes with Duplicate Labels

In [206]:
obj = pd.Series(np.arange(5), index=["a", "a", "b", "b", "c"])
obj

a    0
a    1
b    2
b    3
c    4
dtype: int64

In [207]:
obj.index.is_unique

False

In [208]:
obj["a"]

a    0
a    1
dtype: int64

# Summarizing and Computing Descriptive Statistics

In [209]:
df = pd.DataFrame([[1.4, np.nan], [7.1, -4.5],
                   [np.nan, np.nan], [0.75, -1.3]],
                  index=["a", "b", "c", "d"],
                  columns=["one", "two"])
df

one  two
a  1.40  NaN
b  7.10 -4.5
c   NaN  NaN
d  0.75 -1.3

In [210]:
df.sum()

one    9.25
two   -5.80
dtype: float64

In [211]:
df.sum(axis="columns")

a    1.40
b    2.60
c    0.00
d   -0.55
dtype: float64

In [212]:
df.sum(axis="index",skipna=False)

one   NaN
two   NaN
dtype: float64

In [213]:
df.sum(axis="columns",skipna=False) 

a     NaN
b    2.60
c     NaN
d   -0.55
dtype: float64

In [214]:
df.mean(axis="columns")

a    1.400
b    1.300
c      NaN
d   -0.275
dtype: float64

In [215]:
df.idxmax()

one    b
two    d
dtype: object

In [216]:
df.cumsum()

one  two
a  1.40  NaN
b  8.50 -4.5
c   NaN  NaN
d  9.25 -5.8

In [217]:
df.describe()

one       two
count  3.000000  2.000000
mean   3.083333 -2.900000
std    3.493685  2.262742
min    0.750000 -4.500000
25%    1.075000 -3.700000
50%    1.400000 -2.900000
75%    4.250000 -2.100000
max    7.100000 -1.300000

In [218]:
obj = pd.Series(["a","a","b","c"]*4)
obj.describe()

count     16
unique     3
top        a
freq       8
dtype: object

# Unique Values,Value Counts,and Membership

In [219]:
obj = pd.Series(["c","a","d","a","a","b","b","c","c"])

In [221]:
uniques = obj.unique()
uniques

array(['c', 'a', 'd', 'b'], dtype=object)

In [222]:
uniques.sort()

In [223]:
uniques

array(['a', 'b', 'c', 'd'], dtype=object)

In [224]:
obj.value_counts()

c    3
a    3
b    2
d    1
Name: count, dtype: int64

In [225]:
pd.value_counts(obj.to_numpy(),sort=False)

C:\Users\Irevin\AppData\Local\Temp\ipykernel_21908\1538708888.py:1: FutureWarning: pandas.value_counts is deprecated and will be removed in a future version. Use pd.Series(obj).value_counts() instead.
  pd.value_counts(obj.to_numpy(),sort=False)


c    3
a    3
d    1
b    2
Name: count, dtype: int64

In [226]:
obj

0    c
1    a
2    d
3    a
4    a
5    b
6    b
7    c
8    c
dtype: object

In [227]:
mask=obj.isin(["b","c"])

In [228]:
obj[mask]

0    c
5    b
6    b
7    c
8    c
dtype: object

In [231]:
to_match = pd.Series(["c","a","b","b","c","a"])
unique_vals = pd.Series(["c","b","a"])
indices = pd.Index(unique_vals).get_indexer(to_match)
indices # 可用于预处理中编码转化成数字 

array([0, 2, 1, 1, 0, 2])

In [232]:
data = pd.DataFrame({"Qu1":[1,3,4,3,4],
                     "Qu2":[2,3,1,2,3],
                     "Qu3":[1,5,2,4,4]})
data

Qu1  Qu2  Qu3
0    1    2    1
1    3    3    5
2    4    1    2
3    3    2    4
4    4    3    4

In [235]:
data["Qu1"].value_counts().sort_index()

Qu1
1    1
3    2
4    2
Name: count, dtype: int64

In [236]:
data = pd.DataFrame({"a":[1,1,1,2,2],"b":[0,0,1,0,0]})
data

a  b
0  1  0
1  1  0
2  1  1
3  2  0
4  2  0

In [237]:
data.value_counts()

a  b
1  0    2
2  0    2
1  1    1
Name: count, dtype: int64

Just finished learning the basics of Pandas. Compared to before, I’ve got a much clearer grasp of Series and DataFrame, and I’m more comfortable with the syntax and some of the tricky bits. Still, I’m a long way from using it like a pro. No rush though—keep going, you’ve got this!